            - name: index-now-submit-sitemap-urls-action
  # You may pin to the exact commit or the version.
  # uses: jakob-bagterp/index-now-submit-sitemap-urls-action@4e78b952bf439c2fb06122ae1d70c95dd7522169
  uses: jakob-bagterp/index-now-submit-sitemap-urls-action@v1.0.19
  with:
    # The host of the website. For example: example.com
    host: 
    # The API key for IndexNow. For example: a1b2c3d4
    api_key: 
    # The location of the API key. For example: https://example.com/a1b2c3d4.txt
    api_key_location: 
    # The IndexNow search engine endpoint to submit the sitemap to. If not specified, Bing is used as the default endpoint. And not so important, as the receiving endpoint will propagate the URLs to other IndexNow endpoints, which will then notify the participating search engines). Options: bing, indexnow, naver, seznam, yandex, yep
    endpoint: # optional, default is bing
    # One or more URLs to be submitted. For example a single URL https://example.com or multiple URLs as list "https://example.com/page1 https://example.com/page2".
    urls: # optional, default is 
    # Location of one or more sitemaps to be submitted. For example a single sitemap https://example.com/sitemap.xml or multiple sitemaps as list "https://example.com/sitemap1.xml, https://example.com/sitemap2.xml".
    sitemap_locations: # optional, default is 
    # Filter the sitemap URLs that contain (for example "section1") or match a regular expression (for example "r'(section1)|(section2)'"). Optional.
    sitemap_filter: # optional, default is 
    # Filter the sitemap URLs that have been modified recently as defined by the <lastmod> element in the sitemap. For example 1, 2, or more days ago. Optional.
    sitemap_days_ago: # optional, default is 
          
